[versions]
node-gradle = "7.1.0"
gitSemVer = "7.0.3"

[plugins]
node = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
gitSemVer  = { id = "org.danilopianini.git-sensitive-semantic-versioning", version.ref = "gitSemVer" }

